# Generated by Django 4.1.7 on 2023-03-23 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                  ALTER TABLE search_book DROP COLUMN search_vector;
                  ALTER TABLE search_book ADD COLUMN search_vector tsvector GENERATED ALWAYS AS (
                    setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
                    setweight(to_tsvector('english', coalesce(description,'')), 'B')
                  ) STORED;
                """,
            reverse_sql=None,
        )
    ]
