# Generated by Django 4.1.7 on 2023-03-23 13:53

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0002_auto_20230323_1338"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="book",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="search_vector_idx"
            ),
        ),
    ]
